name: snapenvz
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.12
  - git
  - pip
  - scikit-learn
  - pandas
  - notebook
  - scipy
  - psutil
  - ipywidgets
  - tqdm
  - pip:
    - kaggle
    - snapml==1.11.1
    - bentoml==0.13.1
    - sklearn2pmml
    - xgboost==1.3.3
    - lightgbm==3.1.1

