name: snapenvz
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.12
  - git
  - pip
  - scikit-learn
  - pandas
  - notebook
  - scipy
  - psutil
  - ipywidgets
  - tqdm
  - pip:
    - kaggle
    - snapml
    - bentoml==0.13.1
    - sklearn2pmml
    - xgboost==1.3.3
    - lightgbm==3.1.1
    - sklearn2pmml<=0.85.0
    - skl2onnx==1.8.0
    - onnx
    - onnxmltools==1.9.1
    - joblib<=1.1.0
