name: snapenv2
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8
  - git
  - pip
  - scikit-learn
  - pandas
  - notebook
  - scipy==1.5.2
  - ipywidgets
  - tqdm
  - psutil
  - pip:
    - kaggle
    - snapml==1.7.1
    - scrapbook
