name: snapenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9
  - git
  - pip
  - scikit-learn
  - pandas
  - notebook
  - scipy
  - ipywidgets
  - tqdm
  - psutil
  - matplotlib
  - pip:
    - kaggle
    - snapml==1.14.0
    - xgboost==1.7.4
    - lightgbm==3.1.1
    - scrapbook
    - bentoml==0.13.1
    - sklearn2pmml<=0.85.0
    - skl2onnx==1.8.0
    - onnx
    - onnxmltools==1.9.1
    - joblib<=1.1.0
