name: snapenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.5
  - git
  - pip
  - scikit-learn==0.24.1
  - pandas
  - notebook
  - scipy==1.5.2
  - ipywidgets
  - tqdm
  - psutil
  - pip:
    - kaggle
    - snapml==1.7.1
    - xgboost==1.3.3
    - lightgbm==3.1.1
    - scrapbook
