name: snapenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8
  - git
  - pip
  - scikit-learn
  - pandas
  - notebook
  - scipy
  - ipywidgets
  - tqdm
  - psutil
  - pip:
    - kaggle
    - snapml==1.8.1
    - xgboost==1.3.3
    - lightgbm==3.1.1
    - scrapbook
