name: snapenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9
  - git
  - pip
  - scikit-learn
  - pandas
  - notebook
  - scipy
  - ipywidgets
  - tqdm
  - psutil
  - pip:
    - kaggle
    - snapml==1.11.0
    - xgboost==1.3.3
    - lightgbm==3.1.1
    - scrapbook
    - bentoml==0.13.1
    - sklearn2pmml
